baseURL = "/"
languageCode = "en-gb"
title = "Tim Novis"
theme = "novis"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
[permalinks]
  posts = "/post/:title/"
  pages = "/:title/"
[mediaTypes]
  [mediaTypes."text/javascript"]
    suffixes = ["js", "mjs"]
[taxonomies]
  tag = "tags"