[build.environment]
  HUGO_VERSION = "0.152.2"

[[redirects]]
  from = "/wedding"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSe4h065NtInAv1mChxjFbZqdb9amusVfKR_eE_aAM-Fbomlaw/viewform?usp=dialog"
  status = 200
  force = true
