name = "Novis"
license = "MIT"
licenselink = "https://github.com/timnovis/novis/blob/master/themes/novis/LICENSE.md"
description = "My personal site"
homepage = "https://novis.co/"
tags = []
features = []
min_version = "0.31.1"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
